# GET /api/articles — ресурс возвращает список публикаций;
GET http://localhost:3000/api/articles

###
# GET /api/articles — ресурс возвращает список публикаций с комментарием;
GET http://localhost:3000/api/articles?comments=true

###
# GET /api/articles/:articleId — возвращает полную информацию о публикации;
GET http://localhost:3000/api/articles/65

###
# GET /api/categories — возвращает список категорий;
GET http://localhost:3000/api/categories

###
# GET /api/categories — возвращает список категорий;
GET http://localhost:3000/api/categories?count=true

###
# POST /api/articles — создаёт новую публикацию;
POST http://localhost:3000/api/articles
Content-Type: application/json

{
  "title": "Учим HTML и CSS 2 раза",
  "announce": "Золотое сечение — соотношение двух величин, гармоническая пропорция. Золотое сечение — соотношение двух величин, гармоническая пропорция.",
  "fullText": "Золотое сечение — соотношение двух величин, гармоническая пропорция. Золотое сечение — соотношение двух величин, гармоническая пропорция. Золотое сечение — соотношение двух величин, гармоническая пропорция.",
  "picture": "path_to_image.jpg",
  "userId": 1,
  "categories": [1, 2]
}

###
# PUT /api/articles/:articleId — редактирует определённую публикацию;
PUT http://localhost:3000/api/articles/13
Content-Type: application/json

{
  "title": "НОВОЕ Учим HTML и CSS 2 раза",
  "announce": "НОВОЕ Золотое сечение — соотношение двух величин, гармоническая пропорция. Золотое сечение — соотношение двух величин, гармоническая пропорция.",
  "fullText": "НОВОЕ Золотое сечение — соотношение двух величин, гармоническая пропорция. Золотое сечение — соотношение двух величин, гармоническая пропорция. Золотое сечение — соотношение двух величин, гармоническая пропорция.",
  "categories": ["Музыка", "Программирование"]
}

###
# DELETE /api/articles/:articleId — удаляет определённую публикацию;
DELETE http://localhost:3000/api/articles/112

###
# GET /api/articles/:articleId/comments — возвращает список комментариев определённой публикации;
GET http://localhost:3000/api/articles/98/comments

###
# DELETE /api/articles/:articleId/comments/:commentId — удаляет из определённой публикации комментарий с идентификатором;
DELETE http://localhost:3000/api/articles/5/comments/12

###
# POST /api/articles/VHC3W1/comments — создаёт новый комментарий;
POST http://localhost:3000/api/articles/1/comments
Content-Type: application/json

{
  "text": "Новый комментарий"
}

###
# Поиск
GET http://localhost:3000/api/search?query=Учим
